### ISSUE TITLE
Build fails out of the box

### ISSUE THREAD

**Issue by php4fan** [WalletConnect/walletconnect-example-dapp#92]
I cloned the repository and ran `npm run build`. That's all the instructions tell me to do so I expect that to work out of the box.

I get these errors:
```
> walletconnect-example-dapp@1.7.8 build
> react-scripts-ts build

Creating an optimized production build...
Starting type checking and linting service...
Using 1 worker with 2048MB memory limit
(node:21866) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
(Use `node --trace-deprecation ...` to show where the warning was created)
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:434:10)
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:466:5
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:327:12
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at runSyncOrAsync (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
    at iterateNormalLoaders (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:133
                if(isError) throw e;
                            ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/util/createHash.js:90:53)
    at NormalModule._initBuildHash (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:386:16)
    at handleParseError (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:434:10)
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:466:5
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/webpack/lib/NormalModule.js:327:12
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
    at /home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:236:3
    at context.callback (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at successLoader (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/ts-loader/dist/index.js:51:5)
    at Object.loader (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/ts-loader/dist/index.js:21:12)
    at LOADER_EXECUTION (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/home/teo/Documents/progetti/sandscapes-nft/walletconnect-example-dapp/node_modules/loader-runner/lib/LoaderRunner.js:120:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
```

**Comment by kilogold** [comment]
Same problem. I'm searching for solutions.
