### ISSUE TITLE
WalletConnect is not working on production

### ISSUE THREAD

**Issue by bhandarikishor** [WalletConnect/walletconnect-example-dapp#97]
On production while iam trying to connect to walletconnect it show me QR and showing me below typo

Cannot read properties of undefined (reading 'importKey')
    at main.d9a135fd.js:2:125029
    at f (main.d9a135fd.js:2:727210)
    at Generator._invoke (main.d9a135fd.js:2:726963)
    at Generator.next (main.d9a135fd.js:2:727573)
    at r (main.d9a135fd.js:2:723491)
    at s (main.d9a135fd.js:2:723694)
    at main.d9a135fd.js:2:723753
    at new Promise (<anonymous>)
    at main.d9a135fd.js:2:723634
    at I (main.d9a135fd.js:2:125108)

**Comment by KiSmith777** [comment]
WalletConnect works using https only so if in production, you'll need to install SSL certificates first. If testing in development, you can install local ssl certificates, but I'm sure the implementation is a bit different depending on the framework. If you google "how to enable https localhost (insert framework)" there's plenty of guides out there.

**Comment by bhandarikishor** [comment]
Thank you @KiSmith777 for your valuable time and answer.
